### ISSUE TITLE
inserting into default-constructed flat_set creates null references

### ISSUE THREAD

**Issue by sxeraverx** [boostorg/move#32] opened 2020-04-15 00:23 UTC
The start of the underlying vector of a default-constructed flat_set points to null.

Merging into the flat_set involves converting the iterators to pointers as an optimization for contiguous containers (https://github.com/boostorg/container/blob/develop/include/boost/container/detail/flat_tree.hpp#L130)

However, for a default-constructed flat-set, the pointer underlying `begin()` iterator points to null.

The iterator-to-pointer conversion is done by taking the address of the result of dereferencing the pointer. (https://github.com/boostorg/move/blob/develop/include/boost/move/detail/iterator_to_raw_pointer.hpp#L36-L53)

As an intermediate step, this ends up creating a null reference, which is undefined behavior.

This should probably be fixed by comparing the iterator to a default-constructed iterator and returning nullptr if they compare equal, before attempting to dereference the iterator.

**Comment by sxeraverx** [comment] 2020-04-20 21:05
One more thought--using `iterator_to_raw_pointer` as an optimization for coming up with the end() pointer for a contiguous datastructure also seems broken because it dereferences a one-past-the-end pointer in the process.

**Comment by igaztanaga** [comment] 2020-09-08 12:33
Revising the code, iterator_to_raw_pointer returns the internal pointer via i.operator->(); at least for boost::container::vector, which is the default container. Where is the null reference created?

**Comment by igaztanaga** [comment] 2020-10-20 09:35
Closing as the report misses information and I can't reproduce it (maybe I'm not understanding something important?). Please reopen in case the problem persists.

**Closed by igaztanaga** 2020-10-20 09:35 UTC
